all: README.md

README.md: guessing_game.sh
	echo "## Courseraaa" > README.md
	
	
	echo "\n**Creation date:** `date '+%d/%m/%Y'`\n" >> README.md
	echo "\n**Time:** `date '+%H:%M:%S'`\n" >> README.md
	echo "\n**Number of lines in guessing_game.sh:**" >> README.md
	cat guessing_game.sh | wc -l >> README.md

clean:
	rm README.md